version: '3.8'
services:
    redis:
        image: redis:7-alpine
        container_name: demo-app-redis
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
    stats-worker:
        build:
            context: .
            dockerfile: Dockerfile
            target: ${DOCKER_TARGET:-prod}
        command: pnpm exec pm2-runtime ecosystem.config.js
        environment:
            - REDIS_URL=redis://redis:6379
        depends_on:
            - redis
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
            - REDIS_URL=redis://redis:6379
            - NEXT_PUBLIC_API_URL=https://randomuser.me/api/1.4
        depends_on:
            - redis
        volumes:
            - type: bind
              source: .
              target: /app
              read_only: false
            - /app/node_modules
        profiles:
            - dev
    app-prod:
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - REDIS_URL=redis://redis:6379
            - NEXT_PUBLIC_API_URL=https://randomuser.me/api/1.4
        depends_on:
            - redis
        profiles:
            - prod
volumes:
    redis-data:
